# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '易考助手' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod 'AFNetworking', '~> 3.0'
pod 'Masonry', '~> 0.6.4'
pod 'FMDB', '~> 2.6.2'
pod 'SDWebImage', '~> 3.7.5'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'MJRefresh'


  # Pods for 易考助手

end
